server:
  servlet:
    context-path: /media
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:social_platform_db;MODE=PostgreSQL
    username: 329132
    password: 329132
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
jwt:
  secret: F65hgG#*FGF3r45&^SFertD345Sert%FDF#G345j234fguygwe54f87t*Tgf
  lifetime: 36000000
